### ISSUE TITLE
Restore .templatesyncignore in case of another version in the tpl repository

### ISSUE THREAD

**Issue by msiebeneicher** [AndreasAugustin/actions-template-sync#250]
**Describe the bug**
In case you also handle a `.templatesyncignore` in your tpl repository, for an initial setup or because ~80% of your repositories use a fixed version, you run into merge issues if you have a change in a ignored file.

**To Reproduce**

1. Create tpl repository and include the following files:
  - foo.txt
  - bar.txt
  - foobar.txt
  - .templatesyncignore: |
  foo.txt
 
2. Create child repository and include sync worksflow and the following files:
  - foo.txt
  - bar.txt
  - foobar.txt
  - .templatesyncignore: |
  foo.txt
  bar.txt

3. push a change to the tpl repository `bar.txt` file
4. Execute sync action

**Expected behaviour**
Expected behaviour is now that you have no changes/PR by the actions-template-sync, but you get the change of the bar.txt because the `.templatesyncignore` will be overwritten from the tpl repo before the [git reset](https://github.com/AndreasAugustin/actions-template-sync/blob/main/src/sync_template.sh#L73)

 **Additional context**

A possible solution which I will try out now in https://github.com/AndreasAugustin/actions-template-sync/blob/main/src/sync_template.sh#L58 is this snippet:

```sh
# restore TEMPLATE_SYNC_IGNORE_FILE_NAME in case of a change/diff
# from the tpl repository. The original file in the final repo always wins.
if ! git diff --exit-code "${TEMPLATE_SYNC_IGNORE_FILE_NAME}"; then
  echo "::group::restore ignore file because of incomming changes from tpl repository"
  git restore "${TEMPLATE_SYNC_IGNORE_FILE_NAME}"
  echo "::endgroup::"
fi
```

**Comment by AndreasAugustin** [comment]
Hi @msiebeneicher thanks for the bug report. I will have a look into it soon.

**Comment by AndreasAugustin** [comment]
Hi @msiebeneicher it is definitely a bug but currently I  do not know how to solve it in an algorithm manner.

In some use cases you want exactly this behaviour. E.q. you add new files into the tmpl repo and want to ignore those new files in all child repos. For that you add the newly created file into the tmpl repo `.templatesyncignore` file and propagate this change to all child repositories.

Something like a flag would not help to solve this issue because that flag need to be updated within all child repos.
One option would be to add smth like a configuration file into the tmpl repo where you can decide which behavior you prefer.

Maybe you have some ideas and further thoughts on that, hopefully my thoughts are understandable.

**Remark**

Currently I think the approach you propose is the more valuable one because the other is an edge case. Lets wait until such a feature request is raised.
