### ISSUE TITLE
Failing action in case of existing branch/PR

### ISSUE THREAD

**Issue by msiebeneicher** [AndreasAugustin/actions-template-sync#256]
**Describe the bug**
In case that an actions-template-sync merge branch in already existing, the next action run will fail

**To Reproduce**
Steps to reproduce the behaviour:

1. Create a change in the tpl repo
2. Execute the action to create a PR
3. Execute the action again

**Expected behaviour**
A fast exit 0 if the branch already exists or a fresh start by deleting the existing branch before continue with the existing action

**Comment by AndreasAugustin** [comment]
@msiebeneicher thanks for the report. Yes it is a bug.
Deleting the branch has the disadvantage that also the existing PR need to be revoked. 
That will remove eventual existing discussions within that PR. Am in favor of doing an exit in this case. 

possible implementation:
- check if the remote branch with name <prefix>_<commit_hash> already exists remote if no dryrun is enabled.

**Comment by AndreasAugustin** [comment]
eventually this is fixed with #257 because it won't need the actual version in the `.templateversionrc` anymore on the main branch. It depends on the implementation, but at least the idea should be somehow similar.

**Comment by AndreasAugustin** [comment]
@msiebeneicher this bug should most likely be solved with #264 .
The current issue occurs because the `.templateversionrc` file is not updated on the main target branch.
With #257 the `.templateversionrc` file is not needed anymore because the new algorithm is checking if the last commit hash is present in the current git history. If there is already a PR open with a new branch, this hash will be contained in the history -> will not go to the pull and push, create PR.

Sorry that #264 contains some refactoring, should not have been to keep the PR clean.

**Comment by AndreasAugustin** [comment]
> eventually this will be fixed with #257 because it won't need the actual version in the `.templateversionrc` anymore on the main branch. It depends on the implementation, but at least the idea should be somehow similar.

**Update**
Tested, it does not solve the issue yet. Seems that within github action the information of the new created branch is not given. Need to check how to fix this.
