### ISSUE TITLE
Failing action in case of no changes in template repo

### ISSUE THREAD

**Issue by msiebeneicher** [AndreasAugustin/actions-template-sync#285]
**Describe the bug**
I hit a bug which might be introduced by https://github.com/AndreasAugustin/actions-template-sync/pull/264

In case of no sync is needed, the action will fail and you get a notification via git as a repo maintainer. 
The issue is that "git commit" will exit with code 1 in case of nothing to commit. 

See https://github.com/AndreasAugustin/actions-template-sync/blob/main/src/sync_template.sh#L100

This code snippet solves the issue for me:

```sh
if git diff --quiet && git diff --staged --quiet; then
  info "nothing to commit"
  exit 0
fi

git commit -m "${PR_COMMIT_MSG}"
```

**To Reproduce**
Re-execute the action with no expected changes in template repository.

**Comment by AndreasAugustin** [comment]
thanks for the bug report.
Not sure if it was introduced by #264 . Theoretically this bug was already present because of the `.templatesyncignore` file

- source repo has new changes
- all changes are in files which are located in `.templatesyncignore`
- The check for new changes is now positive because the commit id has changed since last sync
- but all changes will be reverted because those are within `.templatesyncignore`
-> there will be nothing for commit -> error

Thanks also for the code snippet.
