### ISSUE TITLE
[Feat]: additional reviewers for the generated pull requests

### ISSUE THREAD

**Issue by dotdc** [AndreasAugustin/actions-template-sync#359]
### Describe the feature

It would be nice if we could configure the action with a list of additional reviewers for the generated pull requests.
Currently, I think this is only possible using the `CODEOWNERS` file.

### Use Case

This could help with notifications for repositories where `CODEOWNERS` has a detailled configuration based on paths. 

### Proposed Solution

Add a `pr_reviewers` configuration for the generated pull requests.

I'm not very familiar with GitHub action development, but can try to help if needed.

### Acknowledgements

- [ ] I may be able to implement this feature request

**Comment by AndreasAugustin** [comment]
Hi @dotdc thanks a lot for the suggestion.

We could put the configuration into the `templatesync.yml` file (https://github.com/AndreasAugustin/actions-template-sync/blob/main/templatesync.yml) or directly into the workflow definition file (or both).

Because the `templatesync.yml` file currently only supports life-cycle hooks (could be extended) and the main configuration is done within the workflow definition file I think as a starting point we put it into the workflow definition file. 
With fast research I did not find quotas with the possibility to be hit but definitely need to do some further research.
