### ISSUE TITLE
[Bug]: .templatesyncignore file doesn't work in the .github file.

### ISSUE THREAD

**Issue by blu28** [AndreasAugustin/actions-template-sync#405]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I was getting an error about syncing workflow files without workflow permissions, and my attempts to fix it by adding workflow permission failed (maybe an example in the docs is in order?) so I decided to just add .github/workflows directory to a .templatesyncignore file. In order to avoid clutter, I put it in the .github folder, per the documentation. 

When I ran the workflow, I still got the error. I tried moving the same file to the root directory, and that worked, the error went away. 

The .templatsyncignore file looks like this:

# Ignore workflows. They require extra permissions. Better to sync them manually, if at all.
.github/workflows/*

### Expected Behavior

The workflow would run without error.

### Current Behavior

I am getting the workflow permission error.

### Possible Solution

Is it possible the paths in the file need to be relative to its location?

### Template sync version Version

AndreasAugustin/actions-template-sync@v0.4.2-draft

**Comment by AndreasAugustin** [comment]
Hi @blu28 and thanks for the bug report.
I will look into the issue soon.

**Comment by AndreasAugustin** [comment]
Hi @blu28 sorry for letting you wait. Related to your question if an example is in order: So far there is no example in order. The issue is that so far (if it haven't changed recently) rewriting github actions with a github action is not possible (due to security reasons).

This is documented [in troubleshooting section](https://github.com/AndreasAugustin/actions-template-sync#troubleshooting)
![image](https://github.com/AndreasAugustin/actions-template-sync/assets/8027933/d9e13e95-f339-439d-be8a-378e76186bcf)

Related to your bug:

Locally I was not able to reproduce the issue. Also reading the code I was not able to face an issue. I will try to reproduce it on GitHub.

**Comment by blu28** [comment]
If it is not possible to overwrite a Github action from an action, perhaps this action should ignore attempts to overwrite a Github action?

**Comment by AndreasAugustin** [comment]
> If it is not possible to overwrite a Github action from an action, perhaps this action should ignore attempts to overwrite a Github action?

will check that option. Thanks for suggestion :)

**Comment by AndreasAugustin** [comment]
> If it is not possible to overwrite a Github action from an action, perhaps this action should ignore attempts to overwrite a Github action?

**Update**
@blu28 had some time to think about the issue. I remembered why I did not implement a general ignore like you suggested. My statement that you are not able to update an workflow definition file with a github action is not 100% right. It is possible if you use a PAT instead of the built in permissions with `GITHUB_TOKEN`.
This is the reason why it is not a general opt out. -> needs a docs upddate. 

Also related to your mentioned bug. I tested the solution with the latest version. You are using version `v0.4.2-draft`. Can you please update to latest version?
The only "breaking" change:
⚠️ starting with version v1.0.0 the upstream_branch variable default is not `main` anymore. It is now set to the remote default branch.

See: https://github.com/AndreasAugustin/actions-template-sync#release-updates

**Comment by AndreasAugustin** [comment]
@blu28 I see that you have updated the action to `v1.1.8` https://github.com/ToughTechs151/ArrayListExample/actions/runs/7215981214/job/19661294734

Seems your issue is solved?

**Comment by AndreasAugustin** [comment]
> If it is not possible to overwrite a Github action from an action, perhaps this action should ignore attempts to overwrite a Github action?

@blu28 just a small update: Thanks to @jellllly420 and #424 the missing documentation part is now available: https://github.com/AndreasAugustin/actions-template-sync#troubleshooting
