### ISSUE TITLE
Add support for private repositories

### ISSUE THREAD

**Issue by pdrittenhouse** [AndreasAugustin/actions-template-sync#86]
I added this issue for authenticating in a private repo but it looks like private repos aren't supported:

https://github.com/AndreasAugustin/actions-template-sync/issues/84#issuecomment-882145517

It would be awesome to have that feature added.

**Comment by AndreasAugustin** [comment]
@pdrittenhouse thanks a lot for the feature request!
I try to find time this weekend to implement it (together with other features :D )

Regards and happy coding! :rocket:

**Comment by AndreasAugustin** [comment]
@pdrittenhouse sorry (again) that no solution is available yet.
At least I started to think about that issue today.
Am not sure yet how the AUTH can be solved in a nice manner.
I think about using [deploy keys](https://docs.github.com/en/developers/overview/managing-deploy-keys#deploy-keys).
Another option ofc would be to use [Personalised access tokens](https://docs.github.com/en/github/extending-github/git-automation-with-oauth-tokens) which would not need to have a code change. The issue is that those are identity related (persons). Seems a client credentials flow is not available within Github for that use case :(

Using deploy keys (ssh) need some small code changes.

**Comment by AndreasAugustin** [comment]
@all-contributors please add @pdrittenhouse  for ideas

**Comment by AndreasAugustin** [comment]
@pdrittenhouse it is implemented now (finally, again sorry that it took so long, was not a hard task, but my time currently is super limited). Currently `ssh` is implemented, issue added to also support `PAT` #97 
Will be part of next release :+1:
